# Netlify deployment configuration for Rando Website
# This file configures build settings, redirects, and headers for optimal performance

[build]
  # Build command (using our custom build script)
  command = "npm run build"
  
  # Directory to publish (our built files)
  publish = "dist"
  
  # Functions directory (if we add serverless functions later)
  functions = "netlify/functions"

# Build environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Production context settings
[context.production]
  command = "npm run build"
  publish = "dist"

# Deploy preview settings
[context.deploy-preview]
  command = "npm run build"
  publish = "dist"

# Branch deploy settings
[context.branch-deploy]
  command = "npm run build"
  publish = "dist"

# Headers for performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    X-DNS-Prefetch-Control = "on"
    
    # CORS headers for API requests
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Cache headers for static assets
[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache headers for config files (shorter cache)
[[headers]]
  for = "/config/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# HTML cache headers
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirects for SPA behavior (if needed)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://rando-website.netlify.app/*"
  to = "https://rando-website.netlify.app/:splat"
  status = 301
  force = true

# 404 redirect to main page (since it's a single page app)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Edge functions configuration (if using Netlify Edge Functions)
[edge_functions]
  # Example: Add performance monitoring
  # "/api/analytics" = "analytics"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "lighthouse"
    
    [plugins.inputs.audits]
      performance = true
      accessibility = true
      best-practices = true
      seo = true

# Form handling (if we add contact forms later)
[forms]
  # Enable form processing
  # contact = true 